"""added reset password

Revision ID: 27fd82707774
Revises: 6423e788580a
Create Date: 2026-02-22 17:42:27.296929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27fd82707774'
down_revision: Union[str, Sequence[str], None] = '6423e788580a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_code', sa.String(length=4), nullable=True))
    op.add_column('users', sa.Column('new_password', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'new_password')
    op.drop_column('users', 'reset_code')
    # ### end Alembic commands ###
