"""added admin and avatar

Revision ID: 28958fd63aeb
Revises: 27fd82707774
Create Date: 2026-02-22 20:30:01.050272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28958fd63aeb'
down_revision: Union[str, Sequence[str], None] = '27fd82707774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
