"""add email code

Revision ID: 6423e788580a
Revises: e5c8359ff307
Create Date: 2026-02-16 17:40:00.108403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6423e788580a'
down_revision: Union[str, Sequence[str], None] = 'e5c8359ff307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_code', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_code')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
