"""add multi upload

Revision ID: 9733e5bde8fa
Revises: 28958fd63aeb
Create Date: 2026-02-25 11:50:01.296152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9733e5bde8fa'
down_revision: Union[str, Sequence[str], None] = '28958fd63aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_url', sa.String(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.drop_column('posts', 'upload_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('upload_url', sa.VARCHAR(), nullable=True))
    op.drop_table('posts_uploads')
    # ### end Alembic commands ###
